version: "3.7"

services:
  #THIS IS THE NAME OF THE SERVICE THAT SHOULD BE IN THE CONNECTION CREATION FILE
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database
      - POSTGRES_DB=auth
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: auth-service
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/bcrypt/
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
